# This workflow will build, lint and test new commits to master
name: Toy Robot Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install auto formatter and linters
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 flake8 mypy

    - name: Auto format with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive toy_robot

    - name: Type checking with mypy
      run: |
        mypy toy_robot

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 toy_robot --count --ignore=E501

    - name: Test with unittest module
      run: |
        ./unittests.py
        ./integrationtests.py